## GitGuardian / ggshield config
# Strict scanning with minimal noise. Schema: v2
# Docs: https://docs.gitguardian.com/ggshield-docs/configuration/yaml_config

version: 2

secret:
  # Use the CLI (`ggshield secret ignore add ...`) to append precise ignores here.
  ignored_matches: []
  # Path-level ignores. Prefer precise ignores over broad path exclusions.
  ignored_paths: []

# Global options
verbose: false
