## GitGuardian / ggshield config
# Strict scanning with minimal noise. Schema: v2
# Docs: https://docs.gitguardian.com/ggshield-docs/configuration/yaml_config

version: 2

secret:
  # Use the CLI (`ggshield secret ignore add ...`) to append precise ignores here.
  ignored_matches: []
  # Path-level ignores. Prefer precise ignores over broad path exclusions.
  ignored_paths: []

  # Show all secrets in test files to catch hardcoded test credentials
  show_secrets: false

  # Patterns to detect hardcoded passwords in test files
  # This helps catch password="something" patterns that might slip through
  ignored_detectors: []

# Global options
verbose: false
