services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: census
      POSTGRES_USER: census
      POSTGRES_PASSWORD: census
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U census"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgres://census:census@db:5432/census
      SECRET_KEY: change-me-in-env
      ALLOWED_HOSTS: "*"
      DEBUG: "True"
      EXTERNAL_DATASET_API_URL: ${EXTERNAL_DATASET_API_URL:-https://api.rcpch.ac.uk}
      EXTERNAL_DATASET_API_KEY: ${EXTERNAL_DATASET_API_KEY:-}
      # OIDC Configuration for local development
      OIDC_RP_CLIENT_ID_AZURE: ${OIDC_RP_CLIENT_ID_AZURE}
      OIDC_RP_CLIENT_SECRET_AZURE: ${OIDC_RP_CLIENT_SECRET_AZURE}
      OIDC_OP_TENANT_ID_AZURE: ${OIDC_OP_TENANT_ID_AZURE}
      OIDC_RP_CLIENT_ID_GOOGLE: ${OIDC_RP_CLIENT_ID_GOOGLE}
      OIDC_RP_CLIENT_SECRET_GOOGLE: ${OIDC_RP_CLIENT_SECRET_GOOGLE}
      OIDC_RP_SIGN_ALGO: ${OIDC_RP_SIGN_ALGO}
      OIDC_OP_JWKS_ENDPOINT_GOOGLE: ${OIDC_OP_JWKS_ENDPOINT_GOOGLE}
      OIDC_OP_JWKS_ENDPOINT_AZURE: ${OIDC_OP_JWKS_ENDPOINT_AZURE}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    command: sh -lc "npm install && npm run build:css && python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data:
