# Generated by Django 5.2.6 on 2025-09-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0005_auditlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="surveys_aud_scope_623a8c_idx",
            old_name="surveys_au_scope__6fe6f9_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="surveys_aud_created_ec8379_idx",
            old_name="surveys_au_created_39d8c5_idx",
        ),
    ]
