# Generated by Django 5.2.6 on 2025-09-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0008_surveyaccesstoken_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Free text"),
                    ("mc_single", "Multiple choice (single)"),
                    ("mc_multi", "Multiple choice (multi)"),
                    ("likert", "Likert scale"),
                    ("orderable", "Orderable list"),
                    ("yesno", "Yes/No"),
                    ("dropdown", "Dropdown"),
                    ("image", "Image choice"),
                    ("template_patient", "Patient details template"),
                    ("template_professional", "Professional details template"),
                ],
                max_length=50,
            ),
        ),
    ]
