# Generated by Django 5.2.7 on 2025-10-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0011_survey_encryption_option2"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="encrypted_kek_oidc",
            field=models.BinaryField(
                blank=True,
                help_text="Survey encryption key encrypted with OIDC-derived key for automatic unlock",
                null=True,
            ),
        ),
    ]
