# Generated by Django 5.2.7 on 2025-10-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0013_alter_surveymembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="encrypted_kek_org",
            field=models.BinaryField(
                blank=True,
                help_text="Survey encryption key encrypted with organization master key for administrative recovery",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="recovery_shares_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Total number of recovery shares distributed (optional, for Shamir's Secret Sharing)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="recovery_threshold",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of recovery admins required for Shamir's Secret Sharing (optional)",
                null=True,
            ),
        ),
    ]
