# Generated by Django 5.2.7 on 2025-10-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0014_add_org_encryption_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="encrypted_master_key",
            field=models.BinaryField(
                blank=True,
                help_text="Organization master key for administrative recovery of member surveys",
                null=True,
            ),
        ),
    ]
