# Generated by Django 5.2.7 on 2025-10-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0015_add_org_master_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("add", "Add"),
                    ("remove", "Remove"),
                    ("update", "Update"),
                    ("key_recovery", "Key Recovery"),
                ],
                max_length=20,
            ),
        ),
    ]
