# Generated by Django 5.2.7 on 2025-10-26 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0016_add_key_recovery_audit_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the survey was closed (starts retention period)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who closed the survey",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_surveys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When survey was soft deleted (30-day grace period)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="deletion_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when survey data will be automatically deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="hard_deletion_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When survey will be permanently deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="retention_months",
            field=models.IntegerField(
                default=6, help_text="Retention period in months (6-24)"
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="transferred_at",
            field=models.DateTimeField(
                blank=True, help_text="When ownership was transferred", null=True
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="transferred_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous owner if ownership was transferred",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferred_surveys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("creator", "Creator"),
                    ("viewer", "Viewer"),
                    ("data_custodian", "Data Custodian"),
                ],
                default="creator",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LegalHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
                ("authority", models.CharField(max_length=255)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("removal_reason", models.TextField(blank=True)),
                (
                    "placed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_holds_placed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_holds_removed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_hold",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["-placed_at"],
            },
        ),
        migrations.CreateModel(
            name="DataCustodian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custodian_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custodian_revocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_custodians",
                        to="surveys.survey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custodian_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-granted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("user", "survey"),
                        name="uq_active_custodian_per_user_survey",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "download_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("download_url_expires_at", models.DateTimeField()),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("response_count", models.PositiveIntegerField()),
                ("export_format", models.CharField(default="csv", max_length=10)),
                ("is_encrypted", models.BooleanField(default=True)),
                (
                    "encryption_key_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["survey", "-created_at"],
                        name="surveys_dat_survey__bcbbc9_idx",
                    ),
                    models.Index(
                        fields=["download_token"], name="surveys_dat_downloa_ec0479_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataRetentionExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("previous_deletion_date", models.DateTimeField()),
                ("new_deletion_date", models.DateTimeField()),
                ("months_extended", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retention_extension_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retention_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_extensions",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["survey", "-requested_at"],
                        name="surveys_dat_survey__98c37d_idx",
                    )
                ],
            },
        ),
    ]
