# Generated by Django 5.2.7 on 2025-10-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_useroidc"),
    ]

    operations = [
        migrations.AddField(
            model_name="useroidc",
            name="signup_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has completed the signup process (account type selection, etc.)",
            ),
        ),
    ]
