# Generated by Django 5.2.6 on 2025-09-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiongroup",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
