# Generated by Django 5.2.6 on 2025-09-23 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0007_collections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="collectiondefinition",
            name="surveys_collection_unique_key_per_survey",
        ),
        migrations.RenameIndex(
            model_name="collectiondefinition",
            new_name="surveys_col_survey__2f9a47_idx",
            old_name="surveys_col_survey__b64b40_idx",
        ),
        migrations.AddField(
            model_name="survey",
            name="captcha_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="survey",
            name="max_responses",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="no_patient_data_ack",
            field=models.BooleanField(
                default=False,
                help_text="Publisher confirms no patient data is collected when using non-authenticated visibility",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="unlisted_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("authenticated", "Authenticated users only"),
                    ("public", "Public"),
                    ("unlisted", "Unlisted (secret link)"),
                    ("token", "By invite token"),
                ],
                default="authenticated",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="collectiondefinition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectiondefinition",
            unique_together={("survey", "key")},
        ),
        migrations.AddField(
            model_name="surveyaccesstoken",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_access_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="surveyaccesstoken",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_tokens",
                to="surveys.survey",
            ),
        ),
        migrations.AddField(
            model_name="surveyaccesstoken",
            name="used_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_access_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="access_token",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="response",
                to="surveys.surveyaccesstoken",
            ),
        ),
        migrations.AddIndex(
            model_name="surveyaccesstoken",
            index=models.Index(
                fields=["survey", "expires_at"], name="surveys_sur_survey__1d5d6c_idx"
            ),
        ),
    ]
