# Generated by Django 5.2.6 on 2025-09-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0009_alter_surveyquestion_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyQuestionCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("eq", "Equals"),
                            ("neq", "Does not equal"),
                            ("contains", "Contains"),
                            ("not_contains", "Does not contain"),
                            ("gt", "Greater than"),
                            ("gte", "Greater or equal"),
                            ("lt", "Less than"),
                            ("lte", "Less or equal"),
                            ("exists", "Answer provided"),
                            ("not_exists", "Answer missing"),
                        ],
                        default="eq",
                        max_length=16,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Value to compare against the response when required by the operator.",
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("jump_to", "Jump to target"),
                            ("show", "Show target"),
                            ("skip", "Skip target"),
                        ],
                        default="jump_to",
                        max_length=32,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="surveys.surveyquestion",
                    ),
                ),
                (
                    "target_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_conditions",
                        to="surveys.questiongroup",
                    ),
                ),
                (
                    "target_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_conditions",
                        to="surveys.surveyquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["question", "order", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                target_question__isnull=False,
                                target_group__isnull=True,
                            )
                            | models.Q(
                                target_question__isnull=True,
                                target_group__isnull=False,
                            )
                        ),
                        name="surveyquestioncondition_single_target",
                    )
                ],
            },
        ),
    ]
