# Generated by Django 5.2.7 on 2025-10-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0012_add_oidc_encryption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveymembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("creator", "Creator"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=20,
            ),
        ),
    ]
