# Generated by Django 5.2.7 on 2025-11-01 09:49

import checktick_app.surveys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "surveys",
            "0017_survey_closed_at_survey_closed_by_survey_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="retention_months",
            field=models.IntegerField(
                default=checktick_app.surveys.models.get_default_retention_months,
                help_text="Retention period in months (configurable via CHECKTICK_DEFAULT_RETENTION_MONTHS)",
            ),
        ),
    ]
