# Generated by Django 5.2.7 on 2025-10-23 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userlanguagepreference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOIDC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="OIDC provider identifier (e.g., 'google', 'azure')",
                        max_length=100,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Unique subject identifier from the OIDC provider",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the email address has been verified by the OIDC provider",
                    ),
                ),
                (
                    "key_derivation_salt",
                    models.BinaryField(
                        help_text="Unique salt for deriving encryption keys from OIDC identity"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User OIDC Authentication",
                "verbose_name_plural": "User OIDC Authentications",
                "indexes": [
                    models.Index(
                        fields=["provider", "subject"],
                        name="core_useroi_provide_b2af26_idx",
                    )
                ],
            },
        ),
    ]
