name: Build and Publish Docker Images

on:
  push:
    branches: [main]
    tags: ["v*"]
  release:
    types: [published]
  workflow_dispatch: # Allow manual triggers

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Latest tag for main branch
            type=raw,value=latest,enable={{is_default_branch}}
            # Version tags for releases
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            # Short SHA for development
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.registry
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate deployment artifacts
        run: |
          mkdir -p deployment-artifacts
          cp docker-compose.registry.yml deployment-artifacts/docker-compose.yml
          cp .env.selfhost deployment-artifacts/.env.example
          echo "# Census Self-Hosting Quick Start" > deployment-artifacts/README.md
          echo "" >> deployment-artifacts/README.md
          echo "1. Copy .env.example to .env and configure your settings" >> deployment-artifacts/README.md
          echo "2. Run: docker compose up -d" >> deployment-artifacts/README.md
          echo "3. Visit: http://localhost:8000" >> deployment-artifacts/README.md

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v5
        with:
          name: census-deployment-${{ github.ref_name }}
          path: deployment-artifacts/
